/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRevisionRouteImport } from './routes/_authenticated/revision'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as AuthenticatedEnglishIndexRouteImport } from './routes/_authenticated/english.index'
import { Route as AuthenticatedEnglishTutorRouteImport } from './routes/_authenticated/english.tutor'
import { Route as AuthenticatedTestTestIdRouteImport } from './routes/_authenticated/test.$testId'
import { Route as AuthenticatedEnglishLessonLessonIdRouteImport } from './routes/_authenticated/english.lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionRoute = AuthenticatedRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnglishIndexRoute =
  AuthenticatedEnglishIndexRouteImport.update({
    id: '/english/',
    path: '/english/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnglishTutorRoute =
  AuthenticatedEnglishTutorRouteImport.update({
    id: '/english/tutor',
    path: '/english/tutor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestTestIdRoute = AuthenticatedTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnglishLessonLessonIdRoute =
  AuthenticatedEnglishLessonLessonIdRouteImport.update({
    id: '/english/lesson/$lessonId',
    path: '/english/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/english/tutor': typeof AuthenticatedEnglishTutorRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/english/': typeof AuthenticatedEnglishIndexRoute
  '/english/lesson/$lessonId': typeof AuthenticatedEnglishLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/english/tutor': typeof AuthenticatedEnglishTutorRoute
  '/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/english': typeof AuthenticatedEnglishIndexRoute
  '/english/lesson/$lessonId': typeof AuthenticatedEnglishLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/revision': typeof AuthenticatedRevisionRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/_authenticated/english/tutor': typeof AuthenticatedEnglishTutorRoute
  '/_authenticated/test/$testId': typeof AuthenticatedTestTestIdRoute
  '/_authenticated/english/': typeof AuthenticatedEnglishIndexRoute
  '/_authenticated/english/lesson/$lessonId': typeof AuthenticatedEnglishLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/revision'
    | '/chapter/$chapterId'
    | '/subject/$subjectId'
    | '/english/tutor'
    | '/test/$testId'
    | '/english/'
    | '/english/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/revision'
    | '/chapter/$chapterId'
    | '/subject/$subjectId'
    | '/english/tutor'
    | '/test/$testId'
    | '/english'
    | '/english/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/revision'
    | '/chapter/$chapterId'
    | '/subject/$subjectId'
    | '/_authenticated/english/tutor'
    | '/_authenticated/test/$testId'
    | '/_authenticated/english/'
    | '/_authenticated/english/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision': {
      id: '/_authenticated/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AuthenticatedRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/english/': {
      id: '/_authenticated/english/'
      path: '/english'
      fullPath: '/english/'
      preLoaderRoute: typeof AuthenticatedEnglishIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/english/tutor': {
      id: '/_authenticated/english/tutor'
      path: '/english/tutor'
      fullPath: '/english/tutor'
      preLoaderRoute: typeof AuthenticatedEnglishTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test/$testId': {
      id: '/_authenticated/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof AuthenticatedTestTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/english/lesson/$lessonId': {
      id: '/_authenticated/english/lesson/$lessonId'
      path: '/english/lesson/$lessonId'
      fullPath: '/english/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedEnglishLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRevisionRoute: typeof AuthenticatedRevisionRoute
  AuthenticatedEnglishTutorRoute: typeof AuthenticatedEnglishTutorRoute
  AuthenticatedTestTestIdRoute: typeof AuthenticatedTestTestIdRoute
  AuthenticatedEnglishIndexRoute: typeof AuthenticatedEnglishIndexRoute
  AuthenticatedEnglishLessonLessonIdRoute: typeof AuthenticatedEnglishLessonLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRevisionRoute: AuthenticatedRevisionRoute,
  AuthenticatedEnglishTutorRoute: AuthenticatedEnglishTutorRoute,
  AuthenticatedTestTestIdRoute: AuthenticatedTestTestIdRoute,
  AuthenticatedEnglishIndexRoute: AuthenticatedEnglishIndexRoute,
  AuthenticatedEnglishLessonLessonIdRoute:
    AuthenticatedEnglishLessonLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
